### PR TITLE
Updating selecting tools page based on low priority feedback

### PR DESCRIPTION
**Pull request by brianelton**
Updated based on w3c/wai-selecting-eval-tools#34 and w3c/wai-website#466 
Removed draft note.

### CODE REVIEW

**Comment by brianelton** [comment]
I think this falls under https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes
and can be merged.
FYI @kakinney @shawna-slh

**Comment by shawna-slh** [comment]
@brianelton Maybe I'm missing something? my comment: https://github.com/w3c/wai-website/issues/466

**Comment by brianelton** [comment]
> @brianelton Maybe I'm missing something? my comment: [#35 (comment)](https://github.com/w3c/wai-website/issues/466)

I think your comment was added after I created the PR. More work to be done.

**Comment by brianelton** [comment]
I have removed any mention to CI tools. w3c/wai-website#466 is not included in this PR now.

**Comment by shawna-slh** [comment]
@remibetin Brian removed the open change. Others are ready to merge and publish. Then this repo can be moved. Thanks!

**Comment by remibetin** [comment]
@brianelton FYI, this resource's file is now located at https://github.com/w3c/wai-website/blob/master/pages/test-eval/evaluation-tools/selecting-eval-tools.md

cc @shawna-slh

**Pull request merged**
