### PR TITLE
[Future][!!] Accuracy for credibility

### PR DESCRIPTION
**Pull request by shawna-slh**
Web design includes wireframes and early designs in design tools, paper prototypes, and others that cannot be evaluated with these tools. Therefore, that second sentence is not accurate.

### CODE REVIEW

**Comment by yatil** [comment]
I **strongly** disagree. Color contrast tools can be used very early in the design process, for example, and it is something that I personally always try to encourage. As the [definition of throughout](https://en.oxforddictionaries.com/definition/us/throughout) is “In every part of (a place or object)”, I think we are replacing a simple phrase with a synonymous slightly harder to understand word.

**Comment by vavroom** [comment]
I agree with @yatil that tools can, and should, be used very early in the design process.

Spent a bit of time reading up on the difference between through vs throughout. 

The concept of "all phases" or "all stages" is important to spell out. As such, the use of "through" is more appropriate. Assuming the pull request was made with "editor's discrection" in mind, I am closing without merging.

**Comment by shawna-slh** [comment]
Actually, it was marked [!!] not [ED]. :)

I'm still not comfortable with it; however, not enough to hold up this publication. Therefore, I've labelled it "later revision" and added [Future] to the title.

**Comment by vavroom** [comment]
Ok, that was me that missed the fact that two exclamation marks meant not editor discretion.

Happy to revisit in the near future.

Would need to decide whether or not the concept of "all phases" needs to be spelled out or not.

**Pull request closed without merging**
