### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by AndrewArch**
[ED LOW]
Section: Selecting Web Accessibility Evaluation Tools 
Current:  “We cannot check all accessibility aspects automatically. Human judgement is required.”  
– who is “We” when the topic is what the tools can/cannot do? 
Suggesting: “Tools cannot check all accessibility aspects automatically. Human judgement is required.”

### CODE REVIEW

**Comment by shawna-slh** [comment]
@brianelton @kakinney Do you agree that this falls under https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes
and can be merged?

**Comment by brianelton** [comment]
Yes I agree.

**Comment by kakinney** [comment]
I agree too!

**Comment by shawna-slh** [comment]
@remibetin ready to merge

**Pull request merged**
