### PR TITLE
New version for updated tools list

### PR DESCRIPTION
**Pull request by mhansma96**
Updated some descriptions and added information for new filter fields that exist in the new version of the tools list. 

Revision done by Eric Velleman
Put into format and pushed to the Git by Michel Hansma

### CODE REVIEW

**Comment by shawna-slh** [comment]
Hi @mhansma96 If I understand from quick skim, these edits will apply when the new version is published. Therefore, I changed this pull request to "draft" so it doesn't accidentally get merged and published now.

**Comment by mhansma96** [comment]
Hi @shawna-slh that's completely fine I think. This is indeed for the new version. I added the new content based on the update that Eric provided to all of us last week. He asked me to add the new text in a PR already. I've forwarded your response to him as well, so he knows that it's here, and ready to be published when we get to the publication of the new version

**Comment by shawna-slh** [comment]
Thanks.

> and ready to be published when we get to the publication of the new version

Eric probably knows this, so FYI for you: The edits will need to be reviewed by EOWG before they are published.

ping @kakinney :-)

**Comment by shawna-slh** [comment]
will merge & publish with Eval Tools List update redirect

**Comment by shawna-slh** [comment]
to resolve conflict, removed ffi (1.15.5-x64-mingw-ucrt)

**Pull request merged**
